# HOUSE PRICE PREDICTION

In [4]:
import sys
from pathlib import Path

## Import libraries

In [5]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

## Load dataset

In [6]:
df = pd.read_csv("/Applications/Coding/Project's/House Price Prediction /data/house_prices_practice.csv")

## Understand the dataset

In [7]:
df.head()

,Id,OverallQual,GrLivArea,GarageCars,TotalBsmtSF,YearBuilt,FullBath,BedroomAbvGr,LotArea,SalePrice
0,1,7,1560,0,1658,1969,2,1,8059,177106
1,2,4,2827,2,1319,2012,3,4,13530,301044
2,3,8,3920,0,841,2010,1,4,9010,360609
3,4,5,3044,0,1058,1998,0,4,13207,240556
4,5,7,801,1,2428,2020,0,1,9117,193656

In [8]:
df.tail()

,Id,OverallQual,GrLivArea,GarageCars,TotalBsmtSF,YearBuilt,FullBath,BedroomAbvGr,LotArea,SalePrice
295,296,1,3495,1,1792,1954,2,5,4978,250604
296,297,5,3438,3,1266,2003,0,1,9373,329906
297,298,6,1992,0,1148,1996,1,1,7907,184623
298,299,3,3722,1,1407,1998,1,1,8097,303345
299,300,9,1667,0,988,1958,2,1,14553,204982

In [10]:
df.shape

(300, 10)

In [11]:
df.describe

<bound method NDFrame.describe of       Id  OverallQual  GrLivArea  GarageCars  TotalBsmtSF  YearBuilt  \
0      1            7       1560           0         1658       1969
1      2            4       2827           2         1319       2012
2      3            8       3920           0          841       2010
3      4            5       3044           0         1058       1998
4      5            7        801           1         2428       2020
..   ...          ...        ...         ...          ...        ...
295  296            1       3495           1         1792       1954
296  297            5       3438           3         1266       2003
297  298            6       1992           0         1148       1996
298  299            3       3722           1         1407       1998
299  300            9       1667           0          988       1958

     FullBath  BedroomAbvGr  LotArea  SalePrice
0           2             1     8059     177106
1           3             4    13530     301044
2           1             4     9010     360609
3           0             4    13207     240556
4           0             1     9117     193656
..        ...           ...      ...        ...
295         2             5     4978     250604
296         0             1     9373     329906
297         1             1     7907     184623
298         1             1     8097     303345
299         2             1    14553     204982

[300 rows x 10 columns]>

In [12]:
df.info

<bound method DataFrame.info of       Id  OverallQual  GrLivArea  GarageCars  TotalBsmtSF  YearBuilt  \
0      1            7       1560           0         1658       1969
1      2            4       2827           2         1319       2012
2      3            8       3920           0          841       2010
3      4            5       3044           0         1058       1998
4      5            7        801           1         2428       2020
..   ...          ...        ...         ...          ...        ...
295  296            1       3495           1         1792       1954
296  297            5       3438           3         1266       2003
297  298            6       1992           0         1148       1996
298  299            3       3722           1         1407       1998
299  300            9       1667           0          988       1958

     FullBath  BedroomAbvGr  LotArea  SalePrice
0           2             1     8059     177106
1           3             4    13530     301044
2           1             4     9010     360609
3           0             4    13207     240556
4           0             1     9117     193656
..        ...           ...      ...        ...
295         2             5     4978     250604
296         0             1     9373     329906
297         1             1     7907     184623
298         1             1     8097     303345
299         2             1    14553     204982

[300 rows x 10 columns]>

In [13]:
df.dtypes

Id              int64
OverallQual     int64
GrLivArea       int64
GarageCars      int64
TotalBsmtSF     int64
YearBuilt       int64
FullBath        int64
BedroomAbvGr    int64
LotArea         int64
SalePrice       int64
dtype: object

In [15]:
df.isnull().sum()

Id              0
OverallQual     0
GrLivArea       0
GarageCars      0
TotalBsmtSF     0
YearBuilt       0
FullBath        0
BedroomAbvGr    0
LotArea         0
SalePrice       0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.columns

Index(['Id', 'OverallQual', 'GrLivArea', 'GarageCars', 'TotalBsmtSF',
       'YearBuilt', 'FullBath', 'BedroomAbvGr', 'LotArea', 'SalePrice'],
      dtype='str')